### ISSUE TITLE
Intégrer le style

### ISSUE THREAD

**Issue by liZe** [AFPy/pyconfr-2020#2]
Je pense que le logo et les couleurs sont juste parfaites, tu peux te lancer dans le style :smile:. On a avant tout besoin d’avoir quelque chose de correct pour lancer l’appel à sponsors, ce n’est pas grave dans un premier temps si tout n’est pas parfait.

[Proposition logo Pycon Strasbourg 2020.pdf](https://github.com/AFPy/pyconfr-2020/files/4941953/Proposition.logo.Pycon.Strasbourg.2020.pdf)

**Comment by annabellou** [comment]
J'ai intégré le style, changé le logo, les pictos et fait quelques corrections.

C'est pushé sur master !
