### ISSUE TITLE
Mettre en production

### ISSUE THREAD

**Issue by liZe** [AFPy/pyconfr-2020#3]
Je pense que c’est tout bon, au moins pour les sponsors ! On peut à mon avis rediriger `/` vers `/2020/` dès maintenant.

**Comment by JulienPalard** [comment]
Je regarde ça.

**Comment by liZe** [comment]
Yay! https://www.pycon.fr/2020/

**Comment by JulienPalard** [comment]
Yeah ! C'est en prod ! (Ca part automatiquement au push via un github action).
